### PR TITLE
WIP - Introduces a Dangerfile to the project.

### PR DESCRIPTION
**Pull request by xamebax**
Danger helps automating the PR process with some basic, customizable checks defined in a Dangerfile.

This PR introduces the following checks:

- Was a Changelog filled out if there were changes in the code?
- Are there tests?
- Does the PR have a description?
- Is the PR labeled?

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/65)

### CODE REVIEW

**Review by josephholsten — APPROVED** [review]
Generally sounds good. But a comment at the top of the Dangerfile pointing to the doc wouldn’t hurt. 

I get the feeling we’ll be building a suite of common helpers soon!

**Review by josephholsten — DISMISSED** [review]
So do we know why the build isn’t finding the `danger` executable along its path? Do we need to install the gem with bin stubs?

**Comment by MarkGibbons** [comment]
Question about labels, who is expected to add them to the pull request?  The submitter? We might need to add notes about how to contribute.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by xamebax** [comment]
@josephholsten thanks, I modified the travis.yml because `bundle install` didn't run.

@MarkGibbons good point. This is just a proposal for discussion that started [here](https://github.com/sous-chefs/meta/issues/82).

**Comment by rshade** [comment]
can we discuss in sous-chefs slack, I am not sure we want stuff not in chefdk?

**Comment by josephholsten** [comment]
@rshade +1 to synchronous communication. But this is a thing I’ve been investigating for a while. I’d love to know where all the maintainers stand re tools to help them manage incoming tickets.

**Comment by MarkGibbons** [comment]
I think I have the PR clearing tests.  However I would like to see the verbose danger output when danger is run against a pull request.  I don't know how to make that happen yet.  I would value a feature that verified that the cookbook version in metadata had been bumped.  I think the Dangerfile idea makes sense if it's going to be a common or standard thing in the sous-chef environment.  Using the Dangerfile is slightly confusing with another set of error formatting, terminology and assumptions. Does someone like what they see?

**Comment by damacus** [comment]
@MarkGibbons this looks great. 

What're we missing for this to get merged?

**Comment by MarkGibbons** [comment]
We are ready to merge. I wasn't sure if anyone still wanted to do this.  I thought I could merge it but github looks like it's hung up on a review by @josephholsten.

**Review by MarkGibbons — APPROVED** [review]

**Pull request merged**
