### PR TITLE
Fixes broken "Add" functionality of replace_or_add

### PR DESCRIPTION
**Pull request by jblaine**
As is, 0.5.1 (and likely earlier) have a bug where the "or add" functionality of replace_or_add does not work at all.

This patch corrects that bug. I think I introduced it during cleanup of this file a few months back.

### CODE REVIEW

**Comment by jblaine** [comment]
Welp, might as well do it all via the same PR. It was accidental that I pushed the 'Introduce delete_lines' commit to this branch, but hey... free code! I was going to submit a separate PR for that anyway.

**Comment by dougireton** [comment]
:+1: We are hitting this exact bug. Please merge.

**Comment by someara** [comment]
sorry this lingered so long. merged!

**Comment by dougireton** [comment]
Thanks!

**Pull request merged**
