### PR TITLE
Handle an append to an empty file

### PR DESCRIPTION
**Pull request by MarkGibbons**
Deal with the edge case of an empty file.

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/81)

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Fix issue #80

**Comment by damacus** [comment]
I'll fix that danger issue.

**Comment by MarkGibbons** [comment]
thanks, I need help with that one.

**Comment by damacus** [comment]
Well that variable is set in the build log. So whatever. I'm merging!

**Review by damacus — APPROVED** [review]

**Pull request merged**
