### PR TITLE
Use new dokken images, remove chefspec matchers.

### PR DESCRIPTION
**Pull request by xamebax**
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/64)

### CODE REVIEW

**Review by damacus — APPROVED** [review]

**Comment by damacus** [comment]
Thank you!

**Comment by jamietanna** [comment]
Why have ChefSpec matchers been removed? I've just found that this has broken some of my tests, as they were expecting the matchers to remain

**Comment by MarkGibbons** [comment]
Hello @jamietanna,

Sorry that change causes you problems. The matchers were removed once chefspec (version 7.1.0) started to automatically generate matchers.  Chef client 12 support is dropping soon and a recent chefspec with chef-client 13 doesn't need to matchers.  The line cookbook has rspec tests that are intended to show the matchers working.  

See automatic matchers in https://github.com/chefspec/chefspec

**Comment by jamietanna** [comment]
Thanks, that makes sense - I'll be upgrading to 13 soon so shouldn't be too much of an issue to version pin to 1.0.4 in the meantime. Would you accept adding a note in the CHANGELOG to mention this? Just to explain for those that may encounter it

**Comment by MarkGibbons** [comment]
@jamietanna Sure.  Changelog or readme notes in a pull request.

Cheers,
  Mark

**Pull request merged**
