### PR TITLE
Add CircleCI Support (Danger)

### PR DESCRIPTION
**Pull request by damacus**
Danger, high voltage

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/94)

### CODE REVIEW

**Comment by damacus** [comment]
Right I've turn on danger in circleci and made it only build open PRs so danger doesn't complain.

**Review by MarkGibbons — APPROVED** [review]
Nice.

**Comment by MarkGibbons** [comment]
@damacus 

Do you want to release as 1.2.0 or bump to version 2.0?  The edge case of modifying large files will break for large enough files. We did a minor version change for moving append_if_no_line to in memory processing.

thanks,
 Mark

**Comment by damacus** [comment]
Happy to major version bump so no one is surprised by any sort of break.

We should throw that into a changelog.

**Pull request merged**
