### PR TITLE
Fix links in documentation

### PR DESCRIPTION
**Pull request by kitforbes**
### Description

Fixes incorrect URLs found within `CONTRIBUTING.md` and `README.md`. This is purely a cosmetic change.

### Issues Resolved

None.

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line/154)

### CODE REVIEW

**Comment by kitforbes** [comment]
The test failure is due to the new Chef license model.

**Comment by MarkGibbons** [comment]
Thank you for the fixes.  I'll update things to accept the chef infra license and get this merged.

**Comment by damacus** [comment]
@MarkGibbons if you pin the circleci config on version `kitchen@2` then you'll recice the updates that fixes this tomorrow (or whenever I get around to fixing the linting bug)

You'll need to update the lint stage to be called delivery instead :+1:

**Comment by MarkGibbons** [comment]
Finally merged, sorry it took so long.

**Comment by kitforbes** [comment]
No problem at all.

**Pull request merged**
