### PR TITLE
Add file ownership

### PR DESCRIPTION
**Pull request by TheREK3R**
# Description

Add `owner` and `group` properties to resources that will create missing files.

## Issues Resolved

N/a

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by MarkGibbons** [comment]
- It would be consistent with the current documentation to add the owner and group properties to the resource documentation.
- This change looks like it adds owner and group to 2 out 3 of the resources that create a missing file. The filter resource will also create missing files.
- Some future change should probably add the file mode setting to go along with owner and group.

Nice job on the tests BTW.  Thanks

**Comment by TheREK3R** [comment]
You're right, cant believe i missed that. Ill fix it on monday

**Review by MarkGibbons — APPROVED** [review]

**Comment by MarkGibbons** [comment]
thank you for the update

**Comment by kitchen-porter** [comment]
Released as: [4.2.0](https://github.com/sous-chefs/line/releases/tag/4.2.0)

**Pull request merged**
