### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by MarkGibbons**
Missing version change.  Everything else is ready.

Comments solicited if anyone would care to look over the changes.

Windows support.
The remaining resources were converted to process the files in memory instead of line by line.
Fix for #85 and #86

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/87)

### CODE REVIEW

**Comment by MarkGibbons** [comment]
@damacus Would you be against adding appveyor testing for testing the windows support?

**Comment by damacus** [comment]
Build variables being borked again...

**Comment by damacus** [comment]
Appveyor error looks pretty odd.

I'll going to see if we can do a matrix of tests on appveyor too

**Comment by MarkGibbons** [comment]
The appveyor failure might have been one of the random timeouts. It worked on a retry.  I don't know what to do with the danger file error.

**Comment by damacus** [comment]
That's Travis being... Difficult, and not passing in environment variables occasionally. 

I might move that check to AppVeyor or CircleCI (this one is way more reliable and I can set the token globally)

**Pull request merged**
