### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by MarkGibbons**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/108)

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Fully resolves #102

**Comment by damacus** [comment]
I thought the issue templates needed to be in .github?

**Comment by MarkGibbons** [comment]
I'll move them back.  I misunderstood what it was doing and didn't read far enough down in the doc.  I thought putting the templates in the root directories would give people a chance to see the expectations before they did a PR or opened an issue.  They are annoying in the root directory though.


_To add an Issue template to a repository create a file called ISSUE_TEMPLATE in the root directory. A file extension is optional, but Markdown files (.md) are supported. Markdown support makes it easy to add things like headings, links, @-mentions, and task lists to your templates.

Pull Request templates follows the same pattern: add a file called PULL_REQUEST_TEMPLATE to the root directory of your repository.

If you’re worried about the added clutter in the root directory of your project, we also added support for a .github/ folder. You can put CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected._

**Comment by damacus** [comment]
Ah right! They're actually supported in the main directory. Looks a bit messy, and is different from other cookbooks.

**Review by damacus — APPROVED** [review]

**Pull request merged**
